insert into public.portfolio_settings (
  id,
  owner_name,
  role_title,
  hero_title,
  hero_subtitle,
  about_title,
  about_intro,
  about_body,
  location,
  contact_email,
  contact_phone,
  behance_url,
  linkedin_url,
  instagram_url,
  skills,
  software,
  approach,
  updated_at
) values (
  '11111111-1111-4111-8111-111111111111',
  'Omar',
  'Architecture Engineer',
  'Selected Works',
  'Interior architecture and visualization shaped by atmosphere, material clarity, and precise spatial composition.',
  'Architecture engineering with a calm, precise point of view.',
  'Work shaped through concept, drawing, visualization, and careful spatial development.',
  'Omar is an architecture engineer focused on interior concepts, visual atmosphere, and spaces that feel composed, practical, and carefully detailed.

His work moves between concept development, technical understanding, and visualization. Each study develops through material choices, lighting, proportion, and clear spatial storytelling.',
  'Damascus, Syria',
  'omar.architecture@example.com',
  '+963 000 000 000',
  'https://www.behance.net/',
  'https://www.linkedin.com/',
  'https://www.instagram.com/',
  '["Architectural Concept Design", "Spatial Planning", "Design Development", "Architectural Representation", "Physical Modeling", "Research & Analysis"]'::jsonb,
  '["AutoCAD", "Revit", "SketchUp", "Rhino", "Lumion", "Adobe Photoshop", "Adobe InDesign"]'::jsonb,
  '["Research-led concepts", "Clean representation", "Context-aware design"]'::jsonb,
  now()
) on conflict (id) do update set
  owner_name = excluded.owner_name,
  role_title = excluded.role_title,
  hero_title = excluded.hero_title,
  hero_subtitle = excluded.hero_subtitle,
  about_title = excluded.about_title,
  about_intro = excluded.about_intro,
  about_body = excluded.about_body,
  location = excluded.location,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  behance_url = excluded.behance_url,
  linkedin_url = excluded.linkedin_url,
  instagram_url = excluded.instagram_url,
  skills = excluded.skills,
  software = excluded.software,
  approach = excluded.approach,
  updated_at = now();

insert into public.projects (
  id,
  slug,
  title,
  project_number,
  type,
  year,
  location,
  role,
  description,
  concept_statement,
  concept_keywords,
  design_process_steps,
  credits,
  cover_image_url,
  cover_image_alt,
  cover_image_caption,
  cover_orientation,
  sort_order,
  is_published,
  created_at,
  updated_at
) values
(
  '22222222-2222-4222-8222-222222222222',
  'kitchen-interior',
  'Kitchen Interior Study',
  '01',
  'Interior Design',
  '2024',
  'Damascus, Syria',
  'Interior Concept / Visualization',
  'A residential kitchen study with a warm material palette, wood cabinetry, concealed lighting, and compact spatial planning shaped for a refined daily-use interior.',
  'The study balances practical circulation with a calm visual rhythm, using warm wood, integrated lighting, and clean storage lines to make a compact kitchen feel composed and generous.',
  '["Wood", "Concealed light", "Compact plan"]'::jsonb,
  '["Organize storage, preparation, and movement into a clear residential workflow.", "Use warm cabinetry and quiet surfaces to create visual continuity.", "Refine lighting positions to support both function and atmosphere."]'::jsonb,
  'Interior study / Visualization',
  '/projects/kitchen-interior/cover.png',
  'Warm residential kitchen interior with wood cabinetry and concealed lighting',
  'Kitchen interior render',
  'landscape',
  1,
  true,
  now(),
  now()
),
(
  '33333333-3333-4333-8333-333333333333',
  'bathroom-interior',
  'Bathroom Interior Study',
  '02',
  'Interior Visualization',
  '2024',
  'Damascus, Syria',
  'Material Study / Visualization',
  'A luxury bathroom visualization focused on stone surfaces, warm lighting, custom mirrors, and a quiet material atmosphere with high-end residential character.',
  'The composition uses reflective surfaces, soft illumination, and a restrained stone palette to create a bathroom atmosphere that feels calm, precise, and tactile.',
  '["Stone", "Mirror", "Warm light"]'::jsonb,
  '["Set a balanced vanity composition around mirror, basin, and light.", "Develop a material palette with stone texture and warm highlights.", "Frame the render to emphasize depth, reflection, and surface quality."]'::jsonb,
  'Interior study / Visualization',
  '/projects/bathroom-interior/cover.png',
  'Luxury bathroom interior visualization with stone surfaces and warm lighting',
  'Bathroom interior render',
  'portrait',
  2,
  true,
  now(),
  now()
),
(
  '44444444-4444-4444-8444-444444444444',
  'dining-interior',
  'Dining Interior Study',
  '03',
  'Interior Architecture',
  '2024',
  'Damascus, Syria',
  'Interior Concept / Visualization',
  'A refined dining room study organized around symmetry, layered lighting, wall treatments, display shelving, and a polished high-end interior composition.',
  'The dining space is composed as a formal interior scene, using lighting, shelving, and wall articulation to create a balanced atmosphere for gathering.',
  '["Symmetry", "Display", "Dining"]'::jsonb,
  '["Build the room around a centered dining composition and clear sightlines.", "Use wall treatments and shelving to create depth behind the table.", "Layer ceiling and accent lighting to support a refined evening atmosphere."]'::jsonb,
  'Interior study / Visualization',
  '/projects/dining-interior/cover.png',
  'Refined dining room interior with lighting, display shelving, and wall treatments',
  'Dining interior render',
  'landscape',
  3,
  true,
  now(),
  now()
)
on conflict (slug) do update set
  title = excluded.title,
  project_number = excluded.project_number,
  type = excluded.type,
  year = excluded.year,
  location = excluded.location,
  role = excluded.role,
  description = excluded.description,
  concept_statement = excluded.concept_statement,
  concept_keywords = excluded.concept_keywords,
  design_process_steps = excluded.design_process_steps,
  credits = excluded.credits,
  cover_image_url = excluded.cover_image_url,
  cover_image_alt = excluded.cover_image_alt,
  cover_image_caption = excluded.cover_image_caption,
  cover_orientation = excluded.cover_orientation,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published,
  updated_at = now();
